
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.roke.codigo;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int VER = 7;
  public static final int MENOS = 9;
  public static final int MULT = 10;
  public static final int TIPO_TXT = 4;
  public static final int EOF = 0;
  public static final int TIPO_DUVALIN = 3;
  public static final int MAS = 8;
  public static final int VALOR_DECIMAL = 13;
  public static final int ID = 15;
  public static final int DIV = 11;
  public static final int error = 1;
  public static final int ASIGNACION = 5;
  public static final int FIN_SENTENCIA = 6;
  public static final int VALOR_ENTERO = 12;
  public static final int TIPO_NUMERIN = 2;
  public static final int VALOR_TXT = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TIPO_NUMERIN",
  "TIPO_DUVALIN",
  "TIPO_TXT",
  "ASIGNACION",
  "FIN_SENTENCIA",
  "VER",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "VALOR_ENTERO",
  "VALOR_DECIMAL",
  "VALOR_TXT",
  "ID"
  };
}

